use_field_init_shorthand = true
newline_style = "Unix"

# Unstable features below
unstable_features = true
version = "Two"
wrap_comments = true
comment_width = 100
imports_granularity = "Module"
group_imports = "StdExternalCrate"
normalize_comments = true
normalize_doc_attributes = true
